<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = array(
            array("id"=>1,"name"=>"Cambodia","name_kh"=>"កម្ពុជា"),
            array("id"=>14124,"name"=>"Afghanistan"),
            array("id"=>14125,"name"=>"Albania"),
            array("id"=>14126,"name"=>"Algeria"),
            array("id"=>14127,"name"=>"Andorra"),
            array("id"=>14128,"name"=>"Angola"),
            array("id"=>14129,"name"=>"Antigua and Barbuda"),
            array("id"=>14130,"name"=>"Argentina"),
            array("id"=>14131,"name"=>"Armenia"),
            array("id"=>14132,"name"=>"Australia"),
            array("id"=>14133,"name"=>"Austria"),
            array("id"=>14134,"name"=>"Azerbaijan"),
            array("id"=>14135,"name"=>"Bahamas"),
            array("id"=>14136,"name"=>"Bahrain"),
            array("id"=>14137,"name"=>"Bangladesh"),
            array("id"=>14138,"name"=>"Barbados"),
            array("id"=>14139,"name"=>"Belarus"),
            array("id"=>14140,"name"=>"Belgium"),
            array("id"=>14141,"name"=>"Belize"),
            array("id"=>14142,"name"=>"Benin"),
            array("id"=>14143,"name"=>"Bhutan"),
            array("id"=>14144,"name"=>"Bolivia"),
            array("id"=>14145,"name"=>"Bosnia and Herzegovina"),
            array("id"=>14146,"name"=>"Botswana"),
            array("id"=>14147,"name"=>"Brazil"),
            array("id"=>14148,"name"=>"Brunei"),
            array("id"=>14149,"name"=>"Bulgaria"),
            array("id"=>14150,"name"=>"Burkina Faso"),
            array("id"=>14151,"name"=>"Burma/Myanmar"),
            array("id"=>14152,"name"=>"Burundi"),
            array("id"=>14153,"name"=>"Cameroon"),
            array("id"=>14154,"name"=>"Canada"),
            array("id"=>14155,"name"=>"Cape Verde"),
            array("id"=>14156,"name"=>"Central African Republic"),
            array("id"=>14157,"name"=>"Chad"),
            array("id"=>14158,"name"=>"Chile"),
            array("id"=>14159,"name"=>"China"),
            array("id"=>14160,"name"=>"Colombia"),
            array("id"=>14161,"name"=>"Comoros"),
            array("id"=>14162,"name"=>"Congo"),
            array("id"=>14163,"name"=>"Congo, Democratic Republic of"),
            array("id"=>14164,"name"=>"Costa Rica"),
            array("id"=>14165,"name"=>"Cote d'Ivoire/Ivory Coast"),
            array("id"=>14166,"name"=>"Croatia"),
            array("id"=>14167,"name"=>"Cuba"),
            array("id"=>14168,"name"=>"Cyprus"),
            array("id"=>14169,"name"=>"Czech Republic"),
            array("id"=>14170,"name"=>"Denmark"),
            array("id"=>14171,"name"=>"Djibouti"),
            array("id"=>14172,"name"=>"Dominica"),
            array("id"=>14173,"name"=>"Dominican Republic"),
            array("id"=>14174,"name"=>"East Timor"),
            array("id"=>14175,"name"=>"Ecuador"),
            array("id"=>14176,"name"=>"Egypt"),
            array("id"=>14177,"name"=>"El Salvador"),
            array("id"=>14178,"name"=>"Equatorial Guinea"),
            array("id"=>14179,"name"=>"Eritrea"),
            array("id"=>14180,"name"=>"Estonia"),
            array("id"=>14181,"name"=>"Ethiopia"),
            array("id"=>14182,"name"=>"Fiji"),
            array("id"=>14183,"name"=>"Finland"),
            array("id"=>14184,"name"=>"France"),
            array("id"=>14185,"name"=>"Gabon"),
            array("id"=>14186,"name"=>"Gambia"),
            array("id"=>14187,"name"=>"Georgia"),
            array("id"=>14188,"name"=>"Germany"),
            array("id"=>14189,"name"=>"Ghana"),
            array("id"=>14190,"name"=>"Greece"),
            array("id"=>14191,"name"=>"Grenada"),
            array("id"=>14192,"name"=>"Guatemala"),
            array("id"=>14193,"name"=>"Guinea"),
            array("id"=>14194,"name"=>"Guinea-Bissau"),
            array("id"=>14195,"name"=>"Guyana"),
            array("id"=>14196,"name"=>"Haiti"),
            array("id"=>14197,"name"=>"Honduras"),
            array("id"=>14198,"name"=>"Hungary"),
            array("id"=>14199,"name"=>"Iceland"),
            array("id"=>14200,"name"=>"India"),
            array("id"=>14201,"name"=>"Indonesia"),
            array("id"=>14202,"name"=>"Iran"),
            array("id"=>14203,"name"=>"Iraq"),
            array("id"=>14204,"name"=>"Ireland"),
            array("id"=>14205,"name"=>"Israel"),
            array("id"=>14206,"name"=>"Italy"),
            array("id"=>14207,"name"=>"Jamaica"),
            array("id"=>14208,"name"=>"Japan"),
            array("id"=>14209,"name"=>"Jordan"),
            array("id"=>14210,"name"=>"Kazakhstan"),
            array("id"=>14211,"name"=>"Kenya"),
            array("id"=>14212,"name"=>"Kiribati"),
            array("id"=>14213,"name"=>"Korea, North"),
            array("id"=>14214,"name"=>"Korea, South"),
            array("id"=>14215,"name"=>"Kuwait"),
            array("id"=>14216,"name"=>"Kyrgyzstan"),
            array("id"=>14217,"name"=>"Laos"),
            array("id"=>14218,"name"=>"Latvia"),
            array("id"=>14219,"name"=>"Lebanon"),
            array("id"=>14220,"name"=>"Lesotho"),
            array("id"=>14221,"name"=>"Liberia"),
            array("id"=>14222,"name"=>"Libya"),
            array("id"=>14223,"name"=>"Liechtenstein"),
            array("id"=>14224,"name"=>"Lithuania"),
            array("id"=>14225,"name"=>"Luxembourg"),
            array("id"=>14226,"name"=>"Macedonia"),
            array("id"=>14227,"name"=>"Madagascar"),
            array("id"=>14228,"name"=>"Malawi"),
            array("id"=>14229,"name"=>"Malaysia"),
            array("id"=>14230,"name"=>"Maldives"),
            array("id"=>14231,"name"=>"Mali"),
            array("id"=>14232,"name"=>"Malta"),
            array("id"=>14233,"name"=>"Marshall Islands"),
            array("id"=>14234,"name"=>"Mauritania"),
            array("id"=>14235,"name"=>"Mauritius"),
            array("id"=>14236,"name"=>"Mexico"),
            array("id"=>14237,"name"=>"Micronesia"),
            array("id"=>14238,"name"=>"Moldova"),
            array("id"=>14239,"name"=>"Monaco"),
            array("id"=>14240,"name"=>"Mongolia"),
            array("id"=>14241,"name"=>"Montenegro"),
            array("id"=>14242,"name"=>"Morocco"),
            array("id"=>14243,"name"=>"Mozambique"),
            array("id"=>14244,"name"=>"Namibia"),
            array("id"=>14245,"name"=>"Nauru"),
            array("id"=>14246,"name"=>"Nepal"),
            array("id"=>14247,"name"=>"Netherlands"),
            array("id"=>14248,"name"=>"New Zealand"),
            array("id"=>14249,"name"=>"Nicaragua"),
            array("id"=>14250,"name"=>"Niger"),
            array("id"=>14251,"name"=>"Nigeria"),
            array("id"=>14252,"name"=>"Norway"),
            array("id"=>14253,"name"=>"Oman"),
            array("id"=>14254,"name"=>"Pakistan"),
            array("id"=>14255,"name"=>"Palau"),
            array("id"=>14256,"name"=>"Panama"),
            array("id"=>14257,"name"=>"Papua New Guinea"),
            array("id"=>14258,"name"=>"Paraguay"),
            array("id"=>14259,"name"=>"Peru"),
            array("id"=>14260,"name"=>"Philippines"),
            array("id"=>14261,"name"=>"Poland"),
            array("id"=>14262,"name"=>"Portugal"),
            array("id"=>14263,"name"=>"Qatar"),
            array("id"=>14264,"name"=>"Romania"),
            array("id"=>14265,"name"=>"Russian Federation"),
            array("id"=>14266,"name"=>"Rwanda"),
            array("id"=>14267,"name"=>"Saint Kitts and Nevis"),
            array("id"=>14268,"name"=>"Saint Lucia"),
            array("id"=>14269,"name"=>"Saint Vincent and the Grenadines"),
            array("id"=>14270,"name"=>"Samoa"),
            array("id"=>14271,"name"=>"San Marino"),
            array("id"=>14272,"name"=>"Sao Tome and Principe"),
            array("id"=>14273,"name"=>"Saudi Arabia"),
            array("id"=>14274,"name"=>"Senegal"),
            array("id"=>14275,"name"=>"Serbia"),
            array("id"=>14276,"name"=>"Seychelles"),
            array("id"=>14277,"name"=>"Sierra Leone"),
            array("id"=>14278,"name"=>"Singapore"),
            array("id"=>14279,"name"=>"Slovakia"),
            array("id"=>14280,"name"=>"Slovenia"),
            array("id"=>14281,"name"=>"Solomon Islands"),
            array("id"=>14282,"name"=>"Somalia"),
            array("id"=>14283,"name"=>"South Africa"),
            array("id"=>14284,"name"=>"South Sudan"),
            array("id"=>14285,"name"=>"Spain"),
            array("id"=>14286,"name"=>"Sri Lanka"),
            array("id"=>14287,"name"=>"Sudan"),
            array("id"=>14288,"name"=>"Suriname"),
            array("id"=>14289,"name"=>"Swaziland"),
            array("id"=>14290,"name"=>"Sweden"),
            array("id"=>14291,"name"=>"Switzerland"),
            array("id"=>14292,"name"=>"Syria"),
            array("id"=>14293,"name"=>"Tajikistan"),
            array("id"=>14294,"name"=>"Tanzania"),
            array("id"=>14295,"name"=>"Thailand"),
            array("id"=>14296,"name"=>"Togo"),
            array("id"=>14297,"name"=>"Tonga"),
            array("id"=>14298,"name"=>"Trinidad and Tobago"),
            array("id"=>14299,"name"=>"Tunisia"),
            array("id"=>14300,"name"=>"Turkey"),
            array("id"=>14301,"name"=>"Turkmenistan"),
            array("id"=>14302,"name"=>"Tuvalu"),
            array("id"=>14303,"name"=>"Uganda"),
            array("id"=>14304,"name"=>"Ukraine"),
            array("id"=>14305,"name"=>"United Arab Emirates"),
            array("id"=>14306,"name"=>"United Kingdom"),
            array("id"=>14307,"name"=>"United States"),
            array("id"=>14308,"name"=>"Uruguay"),
            array("id"=>14309,"name"=>"Uzbekistan"),
            array("id"=>14310,"name"=>"Vanuatu"),
            array("id"=>14311,"name"=>"Vatican City"),
            array("id"=>14312,"name"=>"Venezuela"),
            array("id"=>14313,"name"=>"Vietnam","name_kh"=>"វៀតណាម"),
            array("id"=>14314,"name"=>"Yemen"),
            array("id"=>14315,"name"=>"Zambia"),
            array("id"=>14316,"name"=>"Zimbabwe")

        );

        $countries_obj = Array();
        foreach($countries as $country){
            $country_obj = array(
                'id'=>$country['id'],
                'name' => $country['name'],
                'create_uid'=>1,
                'created_at'=>Carbon\Carbon::now(),
                'updated_at'=>Carbon\Carbon::now()
            );
            if(isset($country['name_kh'])){
                $country_obj['name_kh'] = $country['name_kh'];
            }
            array_push($countries,$country);
        }

        foreach($countries_obj as $country_obj){
            DB::table('countries')->insert($country_obj);
        }
    }
}
