<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OriginTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $provinces = array(
            array(
                'id'=>1,
                'name_en'=>'Banteay Meanchey',
                'name_kh'=>'បន្ទាយមានជ័យ',
                'name_fr'=>'Banteay Meanchey',
                'code'=>'បជ',
                'prefix'=>'ខេត្ត',
                'is_province' => true,
                'locp_code' => 1,
            ),
            array(
                'id'=>2,
                'name_en'=>'Battambang',
                'name_kh'=>'បាត់ដំបង',
                'name_fr'=>'Battambang',
                'code'=>'បប',
                'prefix'=>'ខេត្ត',
                'is_province' => true,
                'locp_code' => 2,
            ),
            array(
                'id'=>3,
                'name_en'=>'Kampong Cham',
                'name_kh'=>'កំពង់ចាម',
                'name_fr'=>'Kampong Cham',
                'code'=>'កច',
                'prefix'=>'ខេត្ត',
                'is_province' => true,
                'locp_code' => 3,
            ),
            array(
                'id'=>4,
                'name_en'=>'Kampong Chhnang',
                'name_kh'=>'កំពង់ឆ្នាំង',
                'name_fr'=>'Kampong Chhnang',
                'code'=>'កឆ្ន',
                'prefix'=>'ខេត្ត',
                'is_province' => true,
                'locp_code' => 4,
            ),
            array(
                'id'=>5,
                'name_en'=>'Kampong Speu',
                'name_kh'=>'កំពង់ស្ពឺ',
                'name_fr'=>'Kampong Speu',
                'code'=>'កស្ព',
                'prefix'=>'ខេត្ត',
                'is_province' => true,
                'locp_code' => 5,
            ),
            array(
                'id'=>6,
                'name_en'=>'Kampong Thom',
                'name_kh'=>'កំពង់ធំ',
                'name_fr'=>'Kampong Thom',
                'code'=>'កធ',
                'prefix'=>'ខេត្ត',
                'is_province' => true,
                'locp_code' => 6,
            ),
            array(
                'id'=>7,
                'name_en'=>'Kampot',
                'name_kh'=>'កំពត',
                'name_fr'=>'Kampot',
                'code'=>'កព',
                'prefix'=>'ខេត្ត',
                'is_province' => true,
                'locp_code' => 7,
            ),
            array(
                'id'=>8,
                'name_en'=>'Kandal',
                'name_kh'=>'កណ្តាល',
                'name_fr'=>'Kandal',
                'code'=>'កណ',
                'prefix'=>'ខេត្ត',
                'is_province' => true,
                'locp_code' => 8,
            ),
            array(
                'id'=>9,
                'name_en'=>'Koh Kong',
                'name_kh'=>'កោះកុង',
                'name_fr'=>'Koh Kong',
                'code'=>'កក',
                'prefix'=>'ខេត្ត',
                'is_province' => true,
                'locp_code' => 9,
            ),
            array(
                'id'=>10,
                'name_en'=>'Kratie',
                'name_kh'=>'ក្រចេះ',
                'name_fr'=>'Kratié',
                'code'=>'ក្រច',
                'prefix'=>'ខេត្ត',
                'is_province' => true,
                'locp_code' => 10,
            ),
            array(
                'id'=>11,
                'name_en'=>'Mondulkiri',
                'name_kh'=>'មណ្ឌលគីរី',
                'name_fr'=>'Mondulkiri',
                'code'=>'មរ',
                'prefix'=>'ខេត្ត',
                'is_province' => true,
                'locp_code' => 11,
            ),
            array(
                'id'=>12,
                'name_en'=>'Phnom Penh',
                'name_kh'=>'ភ្នំពេញ',
                'name_fr'=>'Phnom Penh',
                'code'=>'ភព',
                'prefix'=>'រាជធានី',
                'is_province' => true,
                'locp_code' => 12,
            ),
            array(
                'id'=>13,
                'name_en'=>'Preah Vihear',
                'name_kh'=>'ព្រះវិហារ',
                'name_fr'=>'Preah Vihear',
                'code'=>'ពហ',
                'prefix'=>'ខេត្ត',
                'is_province' => true,
                'locp_code' => 13,
            ),
            array(
                'id'=>14,
                'name_en'=>'Prey Veng',
                'name_kh'=>'ព្រៃវែង',
                'name_fr'=>'Prey Veng',
                'code'=>'ពវ',
                'prefix'=>'ខេត្ត',
                'is_province' => true,
                'locp_code' => 14,
            ),
            array(
                'id'=>15,
                'name_en'=>'Pursat',
                'name_kh'=>'ពោធិ៍សាត់',
                'name_fr'=>'Pursat',
                'code'=>'ពស',
                'prefix'=>'ខេត្ត',
                'is_province' => true,
                'locp_code' => 15,
            ),
            array(
                'id'=>16,
                'name_en'=>'Ratanakiri',
                'name_kh'=>'រតនគីរី',
                'name_fr'=>'Ratanakiri',
                'code'=>'ររ',
                'prefix'=>'ខេត្ត',
                'is_province' => true,
                'locp_code' => 16,
            ),
            array(
                'id'=>17,
                'name_en'=>'Siem Reap',
                'name_kh'=>'សៀមរាប',
                'name_fr'=>'Siem Reap',
                'code'=>'សរ',
                'prefix'=>'ខេត្ត',
                'is_province' => true,
                'locp_code' => 17,
            ),
            array(
                'id'=>18,
                'name_en'=>'Preah Sihanouk',
                'name_kh'=>'ព្រះសីហនុ',
                'name_fr'=>'Preah Sihanouk',
                'code'=>'សនុ',
                'prefix'=>'ខេត្ត',
                'is_province' => true,
                'locp_code' => 18,
            ),
            array(
                'id'=>19,
                'name_en'=>'Stung Treng',
                'name_kh'=>'ស្ទឹងត្រែង',
                'name_fr'=>'Stung Treng',
                'code'=>'សត',
                'prefix'=>'ខេត្ត',
                'is_province' => true,
                'locp_code' => 19,
            ),
            array(
                'id'=>20,
                'name_en'=>'Svay Rieng',
                'name_kh'=>'ស្វាយរៀង',
                'name_fr'=>'Svay Rieng',
                'code'=>'ស្វរ',
                'prefix'=>'ខេត្ត',
                'is_province' => true,
                'locp_code' => 20,
            ),
            array(
                'id'=>21,
                'name_en'=>'Takeo',
                'name_kh'=>'តាកែវ',
                'name_fr'=>'Takéo',
                'code'=>'តក',
                'prefix'=>'ខេត្ត',
                'is_province' => true,
                'locp_code' => 21,
            ),
            array(
                'id'=>22,
                'name_en'=>'Kep',
                'name_kh'=>'កែប',
                'name_fr'=>'Kep',
                'code'=>'កែប',
                'prefix'=>'ខេត្ត',
                'is_province' => true,
                'locp_code' => 22,
            ),
            array(
                'id'=>23,
                'name_en'=>'Pailin',
                'name_kh'=>'បៃលិន',
                'name_fr'=>'Pailin',
                'code'=>'បល',
                'prefix'=>'ខេត្ត',
                'is_province' => true,
                'locp_code' => 23,
            ),
            array(
                'id'=>24,
                'name_en'=>'Oddar Meanchey',
                'name_kh'=>'ឧត្តរមានជ័យ',
                'name_fr'=>'Oddar Meanchey',
                'code'=>'ឧជ',
                'prefix'=>'ខេត្ត',
                'is_province' => true,
                'locp_code' => 24,
            ),
            array(
                'id'=>25,
                'name_en'=>'Tbong Khmum',
                'name_kh'=>'ត្បូងឃ្មុំ',
                'name_fr'=>'Tbong Khmum',
                'code'=>'តឃ',
                'prefix'=>'ខេត្ត',
                'is_province' => true,
                'locp_code' => 25,
            ),
            array(
                'id'=>26,
                'name_en'=>'Ministry of Education',
                'name_kh'=>'ក្រសួងអប់រំយុវជន និង កីឡា',
                'name_fr'=>'Ministère éducation',
                'code'=>'អយក',
                'prefix'=>'ក្រសួង',
                'is_province' => false,
                'locp_code' => 26,
            ),
            array(
                'id'=>27,
                'name_en'=>'',
                'name_kh'=>'កម្ពុជាក្រោម',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'',
                'is_province' => false,
                'locp_code' => 27,
            ),
            array(
                'id'=>31,
                'name_en'=>'',
                'name_kh'=>'ខាវអ៊ីដាង',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ជំរុំ',
                'is_province' => false,
                'locp_code' => 31,
            ),
            array(
                'id'=>32,
                'name_en'=>'',
                'name_kh'=>'ព្រះត្រពាំង',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ខេត្ត',
                'is_province' => false,
                'locp_code' => 32,
            ),
            array(
                'id'=>33,
                'name_en'=>'',
                'name_kh'=>'សូរិន្ទ',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ខេត្ត',
                'is_province' => false,
                'locp_code' => 33,
            ),
            array(
                'id'=>34,
                'name_en'=>'',
                'name_kh'=>'ជាយដែនកម្ពុជា-ថៃ',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ជំរុំ',
                'is_province' => false,
                'locp_code' => 34,
            ),
            array(
                'id'=>35,
                'name_en'=>'',
                'name_kh'=>'ដងរែក',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ជំរុំ',
                'is_province' => false,
                'locp_code' => 35,
            ),
            array(
                'id'=>36,
                'name_en'=>'',
                'name_kh'=>'តាទុំ',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ជំរុំ',
                'is_province' => false,
                'locp_code' => 36,
            ),
            array(
                'id'=>37,
                'name_en'=>'',
                'name_kh'=>'ណងច័ន្ទ',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ជំរុំ',
                'is_province' => false,
                'locp_code' => 37,
            ),
            array(
                'id'=>38,
                'name_en'=>'',
                'name_kh'=>'ណងឯក',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ជំរុំ',
                'is_province' => false,
                'locp_code' => 38,
            ),
            array(
                'id'=>39,
                'name_en'=>'',
                'name_kh'=>'បាំងភូ',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ជំរុំ',
                'is_province' => false,
                'locp_code' => 39,
            ),
            array(
                'id'=>40,
                'name_en'=>'',
                'name_kh'=>'ឈុនបូរី',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ខេត្ត',
                'is_province' => false,
                'locp_code' => 40,
            ),
            array(
                'id'=>41,
                'name_en'=>'',
                'name_kh'=>'ភ្នំម៉ាឡៃ',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ជំរុំ',
                'is_province' => false,
                'locp_code' => 41,
            ),
            array(
                'id'=>42,
                'name_en'=>'',
                'name_kh'=>'ភ្នំឆ័ត្រ',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ជំរុំ',
                'is_province' => false,
                'locp_code' => 42,
            ),
            array(
                'id'=>43,
                'name_en'=>'',
                'name_kh'=>'សន្តិសុខ',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ជំរុំ',
                'is_province' => false,
                'locp_code' => 43,
            ),
            array(
                'id'=>44,
                'name_en'=>'',
                'name_kh'=>'សម្តេចឪ',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ជំរុំ',
                'is_province' => false,
                'locp_code' => 44,
            ),
            array(
                'id'=>45,
                'name_en'=>'',
                'name_kh'=>'សាយធូ',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ជំរុំ',
                'is_province' => false,
                'locp_code' => 45,
            ),
            array(
                'id'=>46,
                'name_en'=>'',
                'name_kh'=>'សាយប៊ី',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ជំរុំ',
                'is_province' => false,
                'locp_code' => 46,
            ),
            array(
                'id'=>47,
                'name_en'=>'',
                'name_kh'=>'សាយអេក',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ជំរុំ',
                'is_province' => false,
                'locp_code' => 47,
            ),
            array(
                'id'=>48,
                'name_en'=>'',
                'name_kh'=>'សុខសាន្ត',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ជំរុំ',
                'is_province' => false,
                'locp_code' => 48,
            ),
            array(
                'id'=>49,
                'name_en'=>'',
                'name_kh'=>'អំពិល',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ជំរុំ',
                'is_province' => false,
                'locp_code' => 49,
            ),
            array(
                'id'=>50,
                'name_en'=>'',
                'name_kh'=>'ឫទ្ធិសែន',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ជំរុំ',
                'is_province' => false,
                'locp_code' => 50,
            ),
            array(
                'id'=>51,
                'name_en'=>'',
                'name_kh'=>'ទី៧',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ជំរុំ',
                'is_province' => false,
                'locp_code' => 51,
            ),
            array(
                'id'=>52,
                'name_en'=>'',
                'name_kh'=>'ទី៨',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ជំរុំ',
                'is_province' => false,
                'locp_code' => 52,
            ),
            array(
                'id'=>53,
                'name_en'=>'',
                'name_kh'=>'ចិន',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ប្រទេស',
                'is_province' => false,
                'locp_code' => 53,
            ),
            array(
                'id'=>54,
                'name_en'=>'',
                'name_kh'=>'ថៃ',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ប្រទេស',
                'is_province' => false,
                'locp_code' => 54,
            ),
            array(
                'id'=>55,
                'name_en'=>'',
                'name_kh'=>'អាឡឺម៉ង់',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ប្រទេស',
                'is_province' => false,
                'locp_code' => 55,
            ),
            array(
                'id'=>56,
                'name_en'=>'ប៊ុលហ្គារី',
                'name_kh'=>'',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ប្រទេស',
                'is_province' => false,
                'locp_code' => 56,
            ),
            array(
                'id'=>57,
                'name_en'=>'',
                'name_kh'=>'វៀតណាម',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ប្រទេស',
                'is_province' => false,
                'locp_code' => 57,
            ),
            array(
                'id'=>58,
                'name_en'=>'',
                'name_kh'=>'រុស្សី',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'សហព័ន្ធ',
                'is_province' => false,
                'locp_code' => 55,
            ),
            array(
                'id'=>59,
                'name_en'=>'',
                'name_kh'=>'កូរ៉េខាងត្បូង',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ប្រទេស',
                'is_province' => false,
                'locp_code' => 59,
            ),
            array(
                'id'=>60,
                'name_en'=>'',
                'name_kh'=>'អាមេរិក',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'សហរដ្ធ',
                'is_province' => false,
                'locp_code' => 60,
            ),
            array(
                'id'=>61,
                'name_en'=>'',
                'name_kh'=>'អេហ្ស៊ីប',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ប្រទេស',
                'is_province' => false,
                'locp_code' => 61,
            ),
            array(
                'id'=>62,
                'name_en'=>'',
                'name_kh'=>'អូស្ត្រាលី',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ប្រទេស',
                'is_province' => false,
                'locp_code' => 62,
            ),
            array(
                'id'=>63,
                'name_en'=>'',
                'name_kh'=>'កាណាដា',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ប្រទេស',
                'is_province' => false,
                'locp_code' => 63,
            ),
            array(
                'id'=>64,
                'name_en'=>'',
                'name_kh'=>'ញូវហ៊្សេឡង់',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ប្រទេស',
                'is_province' => false,
                'locp_code' => 64,
            ),
            array(
                'id'=>65,
                'name_en'=>'',
                'name_kh'=>'អង់គ្លេស',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ចក្រភព',
                'is_province' => false,
                'locp_code' => 65,
            ),
            array(
                'id'=>66,
                'name_en'=>'',
                'name_kh'=>'ជប៉ុន',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ប្រទេស',
                'is_province' => false,
                'locp_code' => 66,
            ),
            array(
                'id'=>67,
                'name_en'=>'',
                'name_kh'=>'បារាំង',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ប្រទេស',
                'is_province' => false,
                'locp_code' => 67,
            ),
            array(
                'id'=>69,
                'name_en'=>'',
                'name_kh'=>'ឡាវ',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ប្រទេស',
                'is_province' => false,
                'locp_code' => 69,
            ),
            array(
                'id'=>70,
                'name_en'=>'',
                'name_kh'=>'ហុងកុង',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'',
                'is_province' => false,
                'locp_code' => 70,
            ),
            array(
                'id'=>71,
                'name_en'=>'',
                'name_kh'=>'តៃវ៉ាន់',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'',
                'is_province' => false,
                'locp_code' => 71,
            ),
            array(
                'id'=>72,
                'name_en'=>'',
                'name_kh'=>'អ៊ុយក្រែន',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ប្រទេស',
                'is_province' => false,
                'locp_code' => 72,
            ),
            array(
                'id'=>73,
                'name_en'=>'',
                'name_kh'=>'ឥណ្ឌា',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'ប្រទេស',
                'is_province' => false,
                'locp_code' => 73,
            ),
            array(
                'id'=>85,
                'name_en'=>'',
                'name_kh'=>'ផ្សេងៗ( ក្រៅប្រទេស)',
                'name_fr'=>'',
                'code'=>'',
                'prefix'=>'',
                'is_province' => false,
                'locp_code' => 85,
            )


        );

        $origins = array();
        foreach($provinces as $province){
            $origin = array(
                'id'=>$province['id'],
                'name_kh' => $province['name_kh'],
                'name_en' => $province['name_en'],
                'name_fr' => $province['name_fr'],
                'code' => $province['code'],
                'prefix' => $province['prefix'],
                'is_province' => $province['is_province']
            );

            array_push($origins,$origin);
        }

        foreach($origins as $origin){
            DB::table('origins')->insert($origin);
        }
    }
}
