<?php

namespace App\Models\Internship;

use Illuminate\Database\Eloquent\Model;

class Internship extends Model
{
    protected $fillable = [
        'person',
        'company',
        'address',
        'phone',
        'hot_line',
        'e_mail_address',
        'web',
        'title',
        'training_field',
        'start',
        'end',
        'issue_date',
        'is_name'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function internship_student_annuals(){
        return $this->hasMany(InternshipStudentAnnual::class);
    }
}
