<?php

namespace App\Models\Schedule\Timetable;

use App\Models\Schedule\Timetable\Traits\Relationship\SlotRelationship;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Slot
 * @package App\Models\Schedule\Timetable
 */
class Slot extends Model
{
    use SlotRelationship;

    protected $fillable = [
        'time_tp',
        'time_td',
        'time_course',
        'academic_year_d',
        'course_program_id',
        'semester_id',
        'created_uid',
        'write_uid'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function ($model) {
            $model->created_at = auth()->user()->id;
        });

        self::updating(function ($model) {
            $model->write_uid = auth()->user()->id;
        });
    }

    protected $appends = [
        'total_hours'
    ];

    public function getTotalHoursAttribute ()
    {
        if (isset($this->tp)) {
            if ($this->tp > 0) {
                return $this->tp;
            } else if ($this->td > 0) {
                return $this->td;
            } else {
                return $this->tc;
            }
        } else {
            if ($this->time_tp > 0) {
                return $this->time_tp;
            } else if ($this->time_td > 0) {
                return $this->time_td;
            } else {
                return $this->time_course;
            }
        }
    }
}
