<?php

namespace App\Models\Schedule\Timetable;

use App\Models\Schedule\Timetable\Traits\Relationship\SlotRelationship;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Slot
 * @package App\Models\Schedule\Timetable
 */
class Slot extends Model
{
    use SlotRelationship;

    protected $fillable = [
        'time_tp',
        'time_td',
        'time_course',
        'academic_year_d',
        'course_program_id',
        'semester_id',
        'created_uid',
        'write_uid'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function ($model) {
            $model->created_at = auth()->user()->id;
        });

        self::updating(function ($model) {
            $model->write_uid = auth()->user()->id;
        });
    }
}
