<?php

namespace App\Models\Schedule\Timetable;

use App\Models\Schedule\Timetable\Traits\Relationship\TimetableSlotRelationship;
use Illuminate\Database\Eloquent\Model;

/**
 * Class TimetableSlot
 * @package App\Models\Schedule\Timetable
 */
class TimetableSlot extends Model
{
    use TimetableSlotRelationship;

    protected $fillable = [
        'timetable_id',
        'course_program_id',
        'slot_id',
        'lecturer_id',
        'group_id',
        'room_id',
        'group_merge_id',
        'course_name',
        'type',
        'durations',
        'start',
        'end',
        'created_uid',
        'updated_uid'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function ($model) {
            $model->created_uid = auth()->user()->id;
        });

        self::updating(function ($model) {
           $model->updated_uid = auth()->user()->id;
        });
    }
}
