<?php

namespace App\Models\Schedule\Timetable;

use App\Models\Schedule\Timetable\Traits\Relationship\TimetableRelationship;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Timetable
 * @package App\Models\Schedule\Timetable
 */
class Timetable extends Model
{
    use TimetableRelationship;

    protected $fillable = [
        'academic_year_id',
        'department_id',
        'degree_id',
        'grade_id',
        'option_id',
        'semester_id',
        'week_id',
        'completed',
        'created_uid',
        'updated_uid'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function ($model) {
            $model->created_uid = auth()->user()->id;
        });

        self::updating(function ($model) {
            $model->updated_uid = auth()->user()->id;
        });
    }
}
