<?php

namespace App\Models\Schedule\Timetable;

use Illuminate\Database\Eloquent\Model;

class TimetableGroup extends Model
{
    protected $table='timetable_groups';

    protected $fillable = [
        'name_kh',
        'name_en',
        'name_fr',
        'description'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }
}
