<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class DefineAverage extends Model
{
    protected $table="define_averages";

    protected $fillable = [
        'create_uid',
        'write_uid',
        'academic_year_id',
        'department_id',
        'semester_id',
        'option_id',
        'grade_id',
        'degree_id',
        'value'
    ];

    protected $casts = [
        'value' => 'float'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::updating(function ($model) {
            $model->write_uid = auth()->user()->id;
        });

        self::creating(function ($model) {
            $model->create_uid = auth()->user()->id;
            $model->write_uid = auth()->user()->id;
        });
    }
}
